# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


import sys

# prefer official qt bindings
if 'PySide2' in sys.modules:
    from PySide2 import QtWidgets, QtCore
else:
    from PyQt5 import QtWidgets, QtCore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serverLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.serverLabel.setObjectName("serverLabel")
        self.horizontalLayout.addWidget(self.serverLabel)
        self.serverInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.serverInput.setText("")
        self.serverInput.setObjectName("serverInput")
        self.horizontalLayout.addWidget(self.serverInput)
        self.userLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout.addWidget(self.userLabel)
        self.userInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.userInput.setText("")
        self.userInput.setObjectName("userInput")
        self.horizontalLayout.addWidget(self.userInput)
        self.passwdLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.passwdLabel.setObjectName("passwdLabel")
        self.horizontalLayout.addWidget(self.passwdLabel)
        self.passwdInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.passwdInput.setText("")
        self.passwdInput.setObjectName("passwdInput")
        self.horizontalLayout.addWidget(self.passwdInput)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 10, 111, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.portLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout_2.addWidget(self.portLabel)
        self.portInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.portInput.setObjectName("portInput")
        self.horizontalLayout_2.addWidget(self.portInput)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 1131, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.runLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.runLabel.setObjectName("runLabel")
        self.horizontalLayout_6.addWidget(self.runLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.runInfoOutput = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.runInfoOutput.setEnabled(True)
        self.runInfoOutput.setObjectName("runInfoOutput")
        self.verticalLayout_4.addWidget(self.runInfoOutput)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(670, 15, 71, 31))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 1131, 381))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.localLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.localLabel.setObjectName("localLabel")
        self.horizontalLayout_3.addWidget(self.localLabel)
        self.localPathInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.localPathInput.setText("")
        self.localPathInput.setObjectName("localPathInput")
        self.horizontalLayout_3.addWidget(self.localPathInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.localFileList = QtWidgets.QTableView(self.horizontalLayoutWidget_3)
        self.localFileList.setObjectName("localFileList")
        self.verticalLayout_2.addWidget(self.localFileList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.remoteLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.remoteLabel.setObjectName("remoteLabel")
        self.horizontalLayout_5.addWidget(self.remoteLabel)
        self.remotePathInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.remotePathInput.setText("")
        self.remotePathInput.setObjectName("remotePathInput")
        self.horizontalLayout_5.addWidget(self.remotePathInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.remoteFileList = QtWidgets.QTableView(self.horizontalLayoutWidget_3)
        self.remoteFileList.setObjectName("remoteFileList")
        self.verticalLayout_3.addWidget(self.remoteFileList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serverLabel.setText(_translate("MainWindow", "主机"))
        self.userLabel.setText(_translate("MainWindow", "用户名"))
        self.passwdLabel.setText(_translate("MainWindow", "密码"))
        self.portLabel.setText(_translate("MainWindow", "端口号"))
        self.runLabel.setText(_translate("MainWindow", "运行信息"))
        self.connectButton.setText(_translate("MainWindow", "连接"))
        self.localLabel.setText(_translate("MainWindow", "本机路径"))
        self.remoteLabel.setText(_translate("MainWindow", "远程路径"))
